fix a build error with VS 2017
* src\Interface\Interface_STAT.cxx(151): error C2373: "stat": Neudefinition; unterschiedliche Modifizierer
* C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt\sys/stat.h(239): note: Siehe Deklaration von "stat"

(cherry picked from commit 24c05fe0ad1df94c5779ba5351ce7cd9536adec4)